### Register User
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

### Login User
POST http://localhost:5000/login/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

###

### Fetch User's Tweet Feed (Requires Authentication)
GET http://localhost:5000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDI2NDg2NTF9.HCzt5fRtetBwbqLlvdMTNotNiMBVP263su4qzjrXeQg
Content-Type: application/json

###

### Fetch Following List (Requires Authentication)
GET http://localhost:5000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3NDI0NjUyNDl9.H1BI84ExoDsWUGchjX1rTXA1_bkX_dI21bUHIK3D1Tc
Content-Type: application/json

###

### Fetch Followers List (Requires Authentication)
GET http://localhost:5000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDI2NDg2NTF9.HCzt5fRtetBwbqLlvdMTNotNiMBVP263su4qzjrXeQg
Content-Type: application/json

###

### Fetch Tweet Details (Requires Authentication)
GET http://localhost:5000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDI2NDg2NTF9.HCzt5fRtetBwbqLlvdMTNotNiMBVP263su4qzjrXeQg
Content-Type: application/json

###

### Fetch Likes for a Tweet (Requires Authentication)
GET http://localhost:5000/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDI2NDg2NTF9.HCzt5fRtetBwbqLlvdMTNotNiMBVP263su4qzjrXeQg
Content-Type: application/json

###

### Fetch Replies for a Tweet (Requires Authentication)
GET http://localhost:5000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDI2NDg2NTF9.HCzt5fRtetBwbqLlvdMTNotNiMBVP263su4qzjrXeQg
Content-Type: application/json

###

### Fetch User's Tweets (Requires Authentication)
GET http://localhost:5000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3NDI0NjUyNDl9.H1BI84ExoDsWUGchjX1rTXA1_bkX_dI21bUHIK3D1Tc
Content-Type: application/json

###

### Create a Tweet (Requires Authentication)
POST http://localhost:5000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDI2NDg2NTF9.HCzt5fRtetBwbqLlvdMTNotNiMBVP263su4qzjrXeQg
Content-Type: application/json

{
  "tweet": "Hello, this is my first tweet!"
}

###

### Delete a Tweet (Requires Authentication)
DELETE http://localhost:5000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3NDI0NjUyNDl9.H1BI84ExoDsWUGchjX1rTXA1_bkX_dI21bUHIK3D1Tc
Content-Type: application/json
